name: ECR Repository Push

on:
  workflow_dispatch:
    inputs:
      region:
        required: true
        default: ap-northeast-1
        description: Region

jobs:
  ecr-push:
    runs-on: ubuntu-latest
    name: ECR Repository Push
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: containers/php/Dockerfile
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/php_test:latest
